### ISSUE TITLE
2.4.1: IllegalAccessError / NoClassDefFoundError: clojure/lang/IFn

### ISSUE THREAD

**Issue by martinklepsch** [boot-clj/boot#321]
Getting this in a ClojureScript project, working fine with 2.3.0.
```
Writing boot_cljs_repl.cljs...
JNA: Callback com.barbarysoftware.watchservice.MacOSXListeningWatchService$MacOSXListeningCallback@27820d92 threw the following exception:
java.lang.IllegalAccessError: tried to access method com.sun.jna.CallbackParameterContext.<init>(Ljava/lang/Class;Ljava/lang/reflect/Method;[Ljava/lang/Object;I)V from class com.sun.jna.CallbackReference$DefaultCallbackProxy
        at com.sun.jna.CallbackReference$DefaultCallbackProxy.invokeCallback(CallbackReference.java:457)
        at com.sun.jna.CallbackReference$DefaultCallbackProxy.callback(CallbackReference.java:500)
        at com.sun.jna.Native.invokeVoid(Native Method)
        at com.sun.jna.Function.invoke(Function.java:367)
        at com.sun.jna.Function.invoke(Function.java:315)
        at com.sun.jna.Library$Handler.invoke(Library.java:212)
        at com.sun.proxy.$Proxy0.CFRunLoopRun(Unknown Source)
        at com.barbarysoftware.watchservice.MacOSXListeningWatchService$CFRunLoopThread.run(MacOSXListeningWatchService.java:73)
             clojure.lang.ExceptionInfo: java.lang.NoClassDefFoundError: clojure/lang/IFn, compiling:(org/httpkit/server.clj:23:11)
    data: {:file
           "/var/folders/ss/4qg3hk1d4nv40phg1360ng5w0000gn/T/boot.user9145880906787609093.clj",
           :line 23}
java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: clojure/lang/IFn, compiling:(org/httpkit/server.clj:23:11)
clojure.lang.Compiler$CompilerException: java.lang.NoClassDefFoundError: clojure/lang/IFn, compiling:(org/httpkit/server.clj:23:11)
         java.lang.NoClassDefFoundError: clojure/lang/IFn
       java.lang.ClassNotFoundException: clojure.lang.IFn
                                             ...
                            clojure.core/load/fn                          core.clj: 5866
                               clojure.core/load                          core.clj: 5865
                                             ...
                           clojure.core/load-one                          core.clj: 5671
                        clojure.core/load-lib/fn                          core.clj: 5711
                           clojure.core/load-lib                          core.clj: 5710
                                             ...
                              clojure.core/apply                          core.clj:  632
                          clojure.core/load-libs                          core.clj: 5749
                                             ...
                              clojure.core/apply                          core.clj:  632
                            clojure.core/require                          core.clj: 5832
                                             ...
adzerk.boot-reload.server/eval54/loading--auto--                        server.clj:    1
                adzerk.boot-reload.server/eval54                        server.clj:    1
                                             ...
                            clojure.core/load/fn                          core.clj: 5866
                               clojure.core/load                          core.clj: 5865
                                             ...
                           clojure.core/load-one                          core.clj: 5671
                        clojure.core/load-lib/fn                          core.clj: 5711
                           clojure.core/load-lib                          core.clj: 5710
                                             ...
                              clojure.core/apply                          core.clj:  632
                          clojure.core/load-libs                          core.clj: 5749
                                             ...
                              clojure.core/apply                          core.clj:  632
                            clojure.core/require                          core.clj: 5832
                                             ...
                           boot.pod/eval-fn-call                           pod.clj:  182
                               boot.pod/call-in*                           pod.clj:  191
                                             ...
                               boot.pod/call-in*                           pod.clj:  194
                 adzerk.boot-reload/start-server                   boot_reload.clj:   26
                  adzerk.boot-reload/eval1709/fn                   boot_reload.clj:  103
                                             ...
                              clojure.core/apply                          core.clj:  630
                     boot.user/eval1885/fn/fn/fn  boot.user9145880906787609093.clj:   15
                                             ...
                           boot.user/eval1823/fn  boot.user9145880906787609093.clj:   11
                                             ...
                           boot.user/eval1938/fn  boot.user9145880906787609093.clj:   17
                                             ...
                              clojure.core/apply                          core.clj:  630
                       boot.core/construct-tasks                          core.clj:  684
                                             ...
                              clojure.core/apply                          core.clj:  630
                               boot.core/boot/fn                          core.clj:  712
             clojure.core/binding-conveyor-fn/fn                          core.clj: 1916
                                             ...
```

**Comment by martinklepsch** [comment]
Also: https://github.com/martinklepsch/tenzing/issues/44 /cc @talexand

**Comment by martinklepsch** [comment]
Additional new binaries have been added to the 2.4.1 release that should fix this problem: https://github.com/boot-clj/boot/releases/tag/2.4.1
