### ISSUE TITLE
REPL is broken after upgrade to 2.4.1.

### ISSUE THREAD

**Issue by jaccarmac** [boot-clj/boot#320]
I'm running from source and on ed538a73f06f6c730c433cda93dfb86af9a381b8 as of the time of this issue. Running `boot repl` produces the following error trace.

```
             clojure.lang.ExceptionInfo: java.lang.NoClassDefFoundError: clojure/lang/RT, compiling:(mranderson045/toolsreader/v0v9v2/clojure/tools/reader/impl/utils.clj:1:1)
    data: {:file "/tmp/boot.user2560093866596248577.clj", :line 17}
java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: clojure/lang/RT, compiling:(mranderson045/toolsreader/v0v9v2/clojure/tools/reader/impl/utils.clj:1:1)
clojure.lang.Compiler$CompilerException: java.lang.NoClassDefFoundError: clojure/lang/RT, compiling:(mranderson045/toolsreader/v0v9v2/clojure/tools/reader/impl/utils.clj:1:1)
         java.lang.NoClassDefFoundError: clojure/lang/RT
       java.lang.ClassNotFoundException: clojure.lang.RT
                                                                                             ...                        
          mranderson045.toolsreader.v0v9v2.clojure.tools.reader.impl.ExceptionInfo__init.__init0                        
         mranderson045.toolsreader.v0v9v2.clojure.tools.reader.impl.ExceptionInfo__init.<clinit>                        
                                                                                             ...                        
                                                                            clojure.core/load/fn          core.clj: 5866
                                                                               clojure.core/load          core.clj: 5865
                                                                                             ...                        
                                                                           clojure.core/load-one          core.clj: 5671
                                                                        clojure.core/load-lib/fn          core.clj: 5711
                                                                           clojure.core/load-lib          core.clj: 5710
                                                                                             ...                        
                                                                              clojure.core/apply          core.clj:  632
                                                                          clojure.core/load-libs          core.clj: 5749
                                                                                             ...                        
                                                                              clojure.core/apply          core.clj:  632
                                                                            clojure.core/require          core.clj: 5832
                                                                                             ...                        
       mranderson045.toolsreader.v0v9v2.clojure.tools.reader.impl.utils/eval3899/loading--auto--         utils.clj:    9
                       mranderson045.toolsreader.v0v9v2.clojure.tools.reader.impl.utils/eval3899         utils.clj:    9
                                                                                             ...                        
                                                                            clojure.core/load/fn          core.clj: 5866
                                                                               clojure.core/load          core.clj: 5865
                                                                                             ...                        
                                                                           clojure.core/load-one          core.clj: 5671
                                                                        clojure.core/load-lib/fn          core.clj: 5711
                                                                           clojure.core/load-lib          core.clj: 5710
                                                                                             ...                        
                                                                              clojure.core/apply          core.clj:  632
                                                                          clojure.core/load-libs          core.clj: 5749
                                                                                             ...                        
                                                                              clojure.core/apply          core.clj:  634
                                                                                clojure.core/use          core.clj: 5843
                                                                                             ...                        
     mranderson045.toolsreader.v0v9v2.clojure.tools.reader.reader-types/eval3893/loading--auto--  reader_types.clj:    9
                     mranderson045.toolsreader.v0v9v2.clojure.tools.reader.reader-types/eval3893  reader_types.clj:    9
                                                                                             ...                        
                                                                            clojure.core/load/fn          core.clj: 5866
                                                                               clojure.core/load          core.clj: 5865
                                                                                             ...                        
                                                                           clojure.core/load-one          core.clj: 5671
                                                                        clojure.core/load-lib/fn          core.clj: 5711
                                                                           clojure.core/load-lib          core.clj: 5710
                                                                                             ...                        
                                                                              clojure.core/apply          core.clj:  632
                                                                          clojure.core/load-libs          core.clj: 5749
                                                                                             ...                        
                                                                              clojure.core/apply          core.clj:  634
                                                                                clojure.core/use          core.clj: 5843
                                                                                             ...                        
              mranderson045.toolsreader.v0v9v2.clojure.tools.reader.edn/eval3887/loading--auto--           edn.clj:    9
                              mranderson045.toolsreader.v0v9v2.clojure.tools.reader.edn/eval3887           edn.clj:    9
                                                                                             ...                        
                                                                            clojure.core/load/fn          core.clj: 5866
                                                                               clojure.core/load          core.clj: 5865
                                                                                             ...                        
                                                                           clojure.core/load-one          core.clj: 5671
                                                                        clojure.core/load-lib/fn          core.clj: 5711
                                                                           clojure.core/load-lib          core.clj: 5710
                                                                                             ...                        
                                                                              clojure.core/apply          core.clj:  632
                                                                          clojure.core/load-libs          core.clj: 5749
                                                                                             ...                        
                                                                              clojure.core/apply          core.clj:  632
                                                                            clojure.core/require          core.clj: 5832
                                                                                             ...                        
mranderson045.cljfmt.v0v3v0.rewrite-clj.v0v4v12.rewrite-clj.node.string/eval3881/loading--auto--        string.clj:    1
                mranderson045.cljfmt.v0v3v0.rewrite-clj.v0v4v12.rewrite-clj.node.string/eval3881        string.clj:    1
                                                                                             ...                        
                                                                            clojure.core/load/fn          core.clj: 5866
                                                                               clojure.core/load          core.clj: 5865
                                                                                             ...                        
                                                                           clojure.core/load-one          core.clj: 5671
                                                                        clojure.core/load-lib/fn          core.clj: 5711
                                                                           clojure.core/load-lib          core.clj: 5710
                                                                                             ...                        
                                                                              clojure.core/apply          core.clj:  632
                                                                          clojure.core/load-libs          core.clj: 5753
                                                                                             ...                        
                                                                              clojure.core/apply          core.clj:  632
                                                                            clojure.core/require          core.clj: 5832
                                                                                             ...                        
mranderson045.cljfmt.v0v3v0.rewrite-clj.v0v4v12.rewrite-clj.node.coerce/eval3459/loading--auto--        coerce.clj:    1
                mranderson045.cljfmt.v0v3v0.rewrite-clj.v0v4v12.rewrite-clj.node.coerce/eval3459        coerce.clj:    1
                                                                                             ...                        
                                                                            clojure.core/load/fn          core.clj: 5866
                                                                               clojure.core/load          core.clj: 5865
                                                                                             ...                        
                                                                           clojure.core/load-one          core.clj: 5671
                                                                        clojure.core/load-lib/fn          core.clj: 5711
                                                                           clojure.core/load-lib          core.clj: 5710
                                                                                             ...                        
                                                                              clojure.core/apply          core.clj:  632
                                                                          clojure.core/load-libs          core.clj: 5753
                                                                                             ...                        
                                                                              clojure.core/apply          core.clj:  632
                                                                            clojure.core/require          core.clj: 5832
                                                                                             ...                        
       mranderson045.cljfmt.v0v3v0.rewrite-clj.v0v4v12.rewrite-clj.node/eval3453/loading--auto--          node.clj:    1
                       mranderson045.cljfmt.v0v3v0.rewrite-clj.v0v4v12.rewrite-clj.node/eval3453          node.clj:    1
                                                                                             ...                        
                                                                            clojure.core/load/fn          core.clj: 5866
                                                                               clojure.core/load          core.clj: 5865
                                                                                             ...                        
                                                                           clojure.core/load-one          core.clj: 5671
                                                                        clojure.core/load-lib/fn          core.clj: 5711
                                                                           clojure.core/load-lib          core.clj: 5710
                                                                                             ...                        
                                                                              clojure.core/apply          core.clj:  632
                                                                          clojure.core/load-libs          core.clj: 5753
                                                                                             ...                        
                                                                              clojure.core/apply          core.clj:  632
                                                                            clojure.core/require          core.clj: 5832
                                                                                             ...                        
mranderson045.cljfmt.v0v3v0.rewrite-clj.v0v4v12.rewrite-clj.parser.core/eval3447/loading--auto--          core.clj:    1
                mranderson045.cljfmt.v0v3v0.rewrite-clj.v0v4v12.rewrite-clj.parser.core/eval3447          core.clj:    1
                                                                                             ...                        
                                                                            clojure.core/load/fn          core.clj: 5866
                                                                               clojure.core/load          core.clj: 5865
                                                                                             ...                        
                                                                           clojure.core/load-one          core.clj: 5671
                                                                        clojure.core/load-lib/fn          core.clj: 5711
                                                                           clojure.core/load-lib          core.clj: 5710
                                                                                             ...                        
                                                                              clojure.core/apply          core.clj:  632
                                                                          clojure.core/load-libs          core.clj: 5749
                                                                                             ...                        
                                                                              clojure.core/apply          core.clj:  632
                                                                            clojure.core/require          core.clj: 5832
                                                                                             ...                        
     mranderson045.cljfmt.v0v3v0.rewrite-clj.v0v4v12.rewrite-clj.parser/eval3441/loading--auto--        parser.clj:    1
                     mranderson045.cljfmt.v0v3v0.rewrite-clj.v0v4v12.rewrite-clj.parser/eval3441        parser.clj:    1
                                                                                             ...                        
                                                                            clojure.core/load/fn          core.clj: 5866
                                                                               clojure.core/load          core.clj: 5865
                                                                                             ...                        
                                                                           clojure.core/load-one          core.clj: 5671
                                                                        clojure.core/load-lib/fn          core.clj: 5711
                                                                           clojure.core/load-lib          core.clj: 5710
                                                                                             ...                        
                                                                              clojure.core/apply          core.clj:  632
                                                                          clojure.core/load-libs          core.clj: 5749
                                                                                             ...                        
                                                                              clojure.core/apply          core.clj:  632
                                                                            clojure.core/require          core.clj: 5832
                                                                                             ...                        
                                mranderson045.cljfmt.v0v3v0.cljfmt.core/eval3435/loading--auto--          core.clj:    1
                                                mranderson045.cljfmt.v0v3v0.cljfmt.core/eval3435          core.clj:    1
                                                                                             ...                        
                                                                            clojure.core/load/fn          core.clj: 5866
                                                                               clojure.core/load          core.clj: 5865
                                                                                             ...                        
                                                                           clojure.core/load-one          core.clj: 5671
                                                                        clojure.core/load-lib/fn          core.clj: 5711
                                                                           clojure.core/load-lib          core.clj: 5710
                                                                                             ...                        
                                                                              clojure.core/apply          core.clj:  632
                                                                          clojure.core/load-libs          core.clj: 5749
                                                                                             ...                        
                                                                              clojure.core/apply          core.clj:  632
                                                                            clojure.core/require          core.clj: 5832
                                                                                             ...                        
                                          cider.nrepl.middleware.format/eval3429/loading--auto--        format.clj:    1
                                                          cider.nrepl.middleware.format/eval3429        format.clj:    1
                                                                                             ...                        
                                                                            clojure.core/load/fn          core.clj: 5866
                                                                               clojure.core/load          core.clj: 5865
                                                                                             ...                        
                                                                           clojure.core/load-one          core.clj: 5671
                                                                        clojure.core/load-lib/fn          core.clj: 5711
                                                                           clojure.core/load-lib          core.clj: 5710
                                                                                             ...                        
                                                                              clojure.core/apply          core.clj:  632
                                                                          clojure.core/load-libs          core.clj: 5749
                                                                                             ...                        
                                                                              clojure.core/apply          core.clj:  632
                                                                            clojure.core/require          core.clj: 5832
                                                                                             ...                        
                                                             cider.nrepl/eval973/loading--auto--         nrepl.clj:    1
                                                                             cider.nrepl/eval973         nrepl.clj:    1
                                                                                             ...                        
                                                                            clojure.core/load/fn          core.clj: 5866
                                                                               clojure.core/load          core.clj: 5865
                                                                                             ...                        
                                                                           clojure.core/load-one          core.clj: 5671
                                                                        clojure.core/load-lib/fn          core.clj: 5711
                                                                           clojure.core/load-lib          core.clj: 5710
                                                                                             ...                        
                                                                              clojure.core/apply          core.clj:  632
                                                                          clojure.core/load-libs          core.clj: 5749
                                                                                             ...                        
                                                                              clojure.core/apply          core.clj:  632
                                                                            clojure.core/require          core.clj: 5832
                                                                                             ...                        
                                                                          boot.repl-server/->var   repl_server.clj:   51
                                                                      boot.repl-server/->mw-list   repl_server.clj:   57
                                                                             clojure.core/map/fn          core.clj: 2622
                                                                                             ...                        
                                                                                clojure.core/seq          core.clj:  137
                                                                              clojure.core/apply          core.clj:  630
                                                                             clojure.core/mapcat          core.clj: 2660
                                                                                             ...                        
                                                                      boot.repl-server/->mw-list   repl_server.clj:   61
                                                                   boot.repl-server/start-server   repl_server.clj:   70
                                                                                             ...                        
                                                                     boot.task.built-in/fn/fn/fn      built_in.clj:  278
                                                                                             ...                        
                                                                              clojure.core/deref          core.clj: 2206
                                                                  boot.task.built-in/fn/fn/fn/fn      built_in.clj:  282
                                                                             boot.core/run-tasks          core.clj:  701
                                                                               boot.core/boot/fn          core.clj:  711
                                                             clojure.core/binding-conveyor-fn/fn          core.clj: 1916
                                                                                             ...
```

**Comment by jaccarmac** [comment]
A few other commands seem to be broken as well, though I can go through the tutorial (my-project, hello.txt, pom, jar, install, etc.) without trouble.

**Comment by alandipert** [comment]
Thanks for the report, can you share your build.boot or ~/.boot/profile.boot if they seem related to the problem?  I'm not able to reproduce using `boot repl` and no project or configuration.

**Comment by jaccarmac** [comment]
The problem is occurring outside a project. My `profile.boot` is just a simple configuration for CIDER integration.

```
(require 'boot.repl)

(swap! boot.repl/*default-dependencies* concat '[[cider/cider-nrepl "0.10.0-SNAPSHOT"]])
(swap! boot.repl/*default-middleware* conj 'cider.nrepl/cider-middleware)
```

Renaming `profile.boot` allows the REPL to run.

**Comment by martinklepsch** [comment]
@jaccarmac can you try downloading the latest binary for 2.4.1 or rebuilding?

**Comment by micha** [comment]
@jaccarmac can you please re-download [boot.sh](https://github.com/boot-clj/boot/releases/download/2.4.0/boot.sh) and see if the problem persists? Thanks!

**Comment by jaccarmac** [comment]
Fixed, thank you!

**Comment by micha** [comment]
Thanks @jaccarmac, @martinklepsch!
