### ISSUE TITLE
java.lang.NoSuchMethodError: boot.App.getClojureName() after update to 2.2.0

### ISSUE THREAD

**Issue by edannenberg** [boot-clj/boot#266]
Ended up with a version mismatch of boot lib/app after updating to latest release. Cleaned boot cache and .m2 folder but the issue persists. This is on windows with babun(cygwin) but with native boot.exe, also tried from cmd.exe without success. So probably not cygwin related.

```bash
$ boot -h
Boot App Version: 2.0.0-rc4
Boot Lib Version: 2.0.0
Clojure Version:  1.7.0

$ boot -u
...
$ boot -h
Boot App Version: 2.0.0-rc4
Boot Lib Version: 2.2.0
Clojure Version:  1.6.0

$ boot dev
clojure.lang.ExceptionInfo: java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: boot.App.getClojureName()Ljava/lang/String;
    data: {:file
           "C:\\cygwin\\.babun\\cygwin\\tmp\\boot.user3943906731274198144.clj",
           :line 27}
java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: boot.App.getClojureName()Ljava/lang/String;
java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: boot.App.getClojureName()Ljava/lang/String;
            java.lang.NoSuchMethodError: boot.App.getClojureName()Ljava/lang/String;
                  boot.pod/make-pod          pod.clj:  458
     adzerk.boot-reload/make-pod/fn  boot_reload.clj:   15
clojure.core/binding-conveyor-fn/fn         core.clj: 1910
```

**Comment by martinklepsch** [comment]
Through a glitch in the matrix the shell script that has initially been uploaded was defected. The currently linked one should work properly.

**Comment by edannenberg** [comment]
Thanks, all good now.
